version: '2'
services:
  costsegregationapplication-app:
    image: costsegregationapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://costsegregationapplication-postgresql:5432/costSegregationApplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://costsegregationapplication-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://costsegregationapplication-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8080:8080
    depends_on:
      costsegregationapplication-postgresql:
        condition: service_healthy
  costsegregationapplication-postgresql:
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    depends_on:
      - kafka
    extends:
      file: postgresql.yml
      service: costsegregationapplication-postgresql
  costsegregationapplication-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: costsegregationapplication-elasticsearch
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
  kafka:
    depends_on:
      - zookeeper
    restart: on-failure
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    depends_on:
      costsegregationapplication-elasticsearch:
        condition: service_healthy
    extends:
      file: kafka.yml
      service: zookeeper
